name: Build Sample App for CI

on:
  workflow_dispatch:
  pull_request:
    branches: [ "main" ]

jobs:
  build-sample-ci:

    runs-on: windows-latest

    steps:
    - uses: actions/checkout@v4
    - name: Setup .NET
      uses: actions/setup-dotnet@v4
      with:
        dotnet-version: 9.0.x
    - name: Add msbuild to PATH
      uses: microsoft/setup-msbuild@v2
    - name: Install .NET MAUI
      run: dotnet workload install maui-android maui-windows
    - name: Build
      run: msbuild samples\SampleApp\SampleApp.slnx -r -property:Configuration=Release
