name: Build for CI

on:
  workflow_dispatch:
  pull_request:
    branches: [ "main" ]

jobs:
  build-plugin-ci:

    runs-on: windows-latest

    steps:
    - uses: actions/checkout@v4
    - name: Setup .NET
      uses: actions/setup-dotnet@v4
      with:
        dotnet-version: 9.0.x
    - name: Add msbuild to PATH
      uses: microsoft/setup-msbuild@v2
    - name: Install .NET MAUI
      run: dotnet workload install maui
    - name: Build
      run: msbuild Plugin.Maui.Calendar.slnx -r -property:Configuration=Release
    - name: Run Unit Tests
      run: dotnet test tests\Plugin.Maui.Calendar.Tests\Plugin.Maui.Calendar.Tests.csproj --configuration Release --logger trx --collect:"XPlat Code Coverage"
    - name: Upload Test Results
      uses: actions/upload-artifact@v4
      if: always()
      with:
        name: test-results
        path: tests/Plugin.Maui.Calendar.Tests/TestResults/
    - name: Upload Coverage Reports
      uses: actions/upload-artifact@v4
      if: always()
      with:
        name: coverage-report
        path: tests/Plugin.Maui.Calendar.Tests/TestResults/**/coverage.cobertura.xml
