name: Create a release on NuGet

on:
  workflow_dispatch:
  push:
    tags:
    - "v[0-9]+.[0-9]+.[0-9]+"    
jobs:
  release-nuget:
  
    runs-on: windows-latest

    steps:
      - uses: actions/checkout@v4
      - name: Verify commit exists in origin/main
        run: |
          git fetch --no-tags --prune --depth=1 origin +refs/heads/*:refs/remotes/origin/*
          git branch --remote --contains | grep origin/main
      - name: Set VERSION variable from tag
        run: echo "VERSION=${GITHUB_REF/refs\/tags\/v/}" >> $GITHUB_ENV  
      - name: Setup .NET
        uses: actions/setup-dotnet@v4
        with:
         dotnet-version: 9.0.x
      - name: Install .NET MAUI
        run: dotnet workload install maui      
      - name: Get version information from tag
        id: get_version
        uses: battila7/get-version-action@v2
      - name: Build
        run: dotnet build src\Plugin.Maui.Calendar\Plugin.Maui.Calendar.slnx -c Release 
      - name: Pack
        run: dotnet pack src\Plugin.Maui.Calendar\Plugin.Maui.Calendar.slnx -c Release  --no-build --output .
      - name: Push
        run: dotnet nuget push Plugin.Maui.Calendar.*.nupkg -s https://api.nuget.org/v3/index.json -k ${{ secrets.NUGET_API_KEY }}
        env:
          GITHUB_TOKEN: ${{ secrets.NUGET_API_KEY }}
